server.modules   += ( "mod_proxy" )
$HTTP["host"] == "pad.asamblea.social" {
    $HTTP["url"] !~ "^/.well-known" {
        proxy.server  = ( "" => ( (
                                  "host" => "127.0.0.1",
                                  "port" => 9991
                                ) )
                      )
    }
}
