server.modules += ("mod_wstunnel")

$HTTP["host"] == "mumble.asamblea.social" {
    server.document-root = "/opt/mumble-web/dist"

    wstunnel.server = (
        "/mumble" => ((
            "host" => "127.0.0.1",
            "port" => 64738
        ))
    )
    wstunnel.ping-interval = 0
}

$SERVER["socket"] == ":443" {
    $HTTP["host"] == "mumble.asamblea.social" {
        ssl.pemfile = "/etc/letsencrypt/live/mumble.asamblea.social/fullchain.pem"
        ssl.privkey = "/etc/letsencrypt/live/mumble.asamblea.social/privkey.pem"
    }
}
