server.modules += ("mod_wstunnel")
server.modules += ("mod_proxy")

$HTTP["host"] == "voz.asamblea.social" {
    server.document-root = "/opt/voz-asamblea/dist"

    wstunnel.server = (
        "/mumble" => ((
            "host" => "127.0.0.1",
            "port" => 64738
        ))
    )
    wstunnel.ping-interval = 0

    proxy.server = (
        "/auth-bridge/" => ((
            "host" => "127.0.0.1",
            "port" => 8091
        ))
    )
}

$SERVER["socket"] == ":443" {
    $HTTP["host"] == "voz.asamblea.social" {
        ssl.pemfile = "/etc/letsencrypt/live/voz.asamblea.social/fullchain.pem"
        ssl.privkey = "/etc/letsencrypt/live/voz.asamblea.social/privkey.pem"
    }
}
